title = "Pulse Parametrization for Krotov's Method"
tags = ["krotov", "optimization"]
author = "Michael Goerz"
file = "krotov_pulse_parametrization.jl"
deploy = ["*.png"]
assets = ["plots"]
threads = 1
order = 101
